---

- name: extract usernames from paths
  set_fact:
    deny_users: "{{ item.path | basename }}"
  with_items: "{{ users.files }}"
  register: path_users 

- name: edit ssh permissions for users
  lineinfile: 
    path: /etc/ssh/sshd_config
    regexp: '^DenyUsers/s'
    line: "DenyUsers {{ path_users.results | map(attribute='ansible_facts.deny_users') | join(' ') }}"
  become: yes
  notify: sshd restart
  tags:
    - ssh
    - docdoc
